version: 2.1

executors:
  default-jvm:
    working_directory: ~/repo/pretty-jupiter

    docker:
      - image: circleci/openjdk:15-jdk-buster
        environment:
          JVM_OPTS: -Xmx4096m
          TERM: dumb

commands:
  setup:
    description: "Setup the environment to run tasks on CI"

    steps:
      - checkout:
          path: ~/repo/pretty-jupiter

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}
            - v2-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-
            - v2-dependencies-

  store-cache:
    description: "Store Gradle configuration and dependencies in cache"

    steps:
      - save_cache:
          paths:
            - ~/repo/pretty-jupiter/.gradle
            - ~/.gradle
          key: v2-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}

jobs:
  build:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Compile
          command: ./gradlew compileGroovy compileTestGroovy compileE2eGroovy

      - run:
          name: Lint
          command: ./gradlew codenarcMain codenarcTest

      - run:
          name: Test
          command: ./gradlew test

      - run:
          name: End-to-end
          command: ./gradlew e2e

      - run:
          name: Build
          command: ./gradlew build

      - store-cache

      - run:
          name: Generate reports
          command: ./gradlew jacocoTestReport

      - run:
          name: Upload reports
          command: bash <(curl -s https://codecov.io/bash) -y ./.circleci/codecov.yml

  publish:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Assemble
          command: ./gradlew assemble

      - run:
          name: Publish
          command: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

workflows:
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: release
