name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 22
          check-latest: true
      - uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/dependency-submission@v4
      - run: ./gradlew compileJava compileTestJava compileTestkitJava
      - run: ./gradlew checkstyleMain checkstyleTest checkstyleTestkit
      - run: ./gradlew sonarlintMain sonarlintTest sonarlintTestkit
      - run: ./gradlew test
      - run: ./gradlew testkit
      - run: ./gradlew build
      - run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
