---
name: Release

on:
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 20
          check-latest: true
          cache: gradle
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Provision
        run: |
          sed -i "s/{GRADLE_PUBLISH_KEY}/${{ secrets.GRADLE_PUBLISH_KEY }}/g" gradle.properties
          sed -i "s/{GRADLE_PUBLISH_SECRET}/${{ secrets.GRADLE_PUBLISH_SECRET }}/g" gradle.properties
      - run: ./gradlew build
      - run: yarn install --immutable
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pages:
    uses: ./.github/workflows/pages.yml
    needs: deploy
